### ISSUE TITLE
Enforce reviews before PR merges

### ISSUE THREAD

**Issue by danyim** [sohbr/cookie_jar#10]
https://help.github.com/articles/enabling-required-reviews-for-pull-requests/

Please follow the guide and enable the mandatory review for pull requests. You may have to check the box for allowing administrators (not only code owners) to approve changes. On that note, could you make sure I am an administrator for this repo?

**Comment by sohbr** [comment]
I enabled branch protection. I made you a collaborator before but I don't think I can make you an admin. Looks like that is an option when it comes to organizations.
